### ISSUE TITLE
Sample program for configuring AWS Cloudwatch in spring boot 2 application

### ISSUE THREAD

**Issue by mghildiy** [micrometer-metrics/micrometer-samples-spring-boot#2]
Hi,

Can we have a sample program on how to configure AWS cloudwatch for micrometer in Spring boot 2 application?
For other systems, it is documented [here](https://micrometer.io/docs), but not for AWS Cloudwatch.

Meanwhile I am also trying to get it done in my project. If I am successful , I would create a PR for same.

@jkschneider 

With regards
Manish

**Comment by jmaciasluque** [comment]
+1

**Comment by pbthorste** [comment]
Here is a setup that works for me.

Using spring boot 2.0.3.

Add these dependencies:

```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-aws-actuator</artifactId>
    <version>2.0.0.RELEASE</version>
</dependency>
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-aws</artifactId>
    <version>2.0.0.RELEASE</version>
</dependency>
```
application.yml:
```yaml
# you might want to set this to true depending on your setup
cloud.aws.stack.auto: false
# set static region to avoid s3 error - adjust region accordingly
cloud.aws.region.static: eu-west-1
management:
  metrics.export.cloudwatch.namespace: my-app
  metrics.export.cloudwatch.batch-size: 20
```
